layout_spectrum: 1
name: Baligotravel
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.9825454
  lightness: 0.9659575
  saturation: 0.3943577
  rhythmicContrast: 0.9839134
  brandColors:
    - '#FFFFFF'
    - '#01FFFF'
    - '#C48F2D'
    - '#FD1632'
    - '#2F1F20'
typography_spectrum: 0.5170213
